### PR TITLE
Convert ipynb to md via jupytext

### PR DESCRIPTION
**Pull request by rdmolony**
Surprisingly jupyter-book works out of the box with the current
documentation setup.  It looks pretty much identical to the
current docs but with the added bonus of a rocket ship code
runner button:

image

To reproduce run:

```bash
$ pip install jupyter-book
$ jupyter-book build .
```

---

- [ ] Decide on how cell outputs will be handled (see table of options below)
- [ ] Migrate ipynb to md (specifically MySt) & fix broken image references
  - [x] beginner/ 
  - [x] extensions/
  - [x] fugue_sql/
  - [ ] advanced/
  - [ ] examples/
  - [ ] applications/
  - [ ] appendix/
- [x] Create a Github Action to publish - see #81

### CODE REVIEW

**Comment by rdmolony** [comment]
I'm experimenting with converting the ipynb to md via jupytext and then running jupyter-book on the markdown files

**Comment by rdmolony** [comment]
beginner/ books are now all saved as markdown and executable via jupyter-book with the caveat that output is no longer stored.

Options:
- execute the notebooks at compile time via _config.yml
```yaml
title: "Fugue Tutorials"
...
execute:
  execute_notebooks: "on"
```
- OR save cell output in the markdown files

**Comment by rdmolony** [comment]
Also see https://jupyterbook.org/file-types/myst-notebooks.html

**Comment by rdmolony** [comment]
beginner/introduction.md now behaves in the same manner as the production docs by generating cell outputs at runtime via jupyter-book albeit with a little more information:

image

Encouragingly it was possible to suppress stdout and stderr for spark warnings that would just confuse otherwise:
```bash
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/Users/rowanm/mambaforge/envs/fugue-docs/lib/python3.9/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
21/09/19 17:18:12 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
```

**Comment by rdmolony** [comment]
I can't work out how to cross-reference images as `` is no longer working

**Comment by rdmolony** [comment]
See https://github.com/executablebooks/jupyter-book/issues/790

**Comment by rdmolony** [comment]
Is it okay to have an images/ directory that lives alongside the notebooks in `tutorials/beginner/*`?

**Comment by rdmolony** [comment]
I've migrated beginner/ to `MyST` with the same outputs as production docs

**Comment by kvnkho** [comment]
> Is it okay to have an images/ directory that lives alongside the notebooks in `tutorials/beginner/*`?

Yes I think it is because images are indeed difficult to render sometimes (they don't make it to ReadTheDocs). From experience, I've hacked it by placing the images in a notebook in the `legacy` folder, which seems to force it to upload. I think the specific scenario in which this occurs is using an <HTML> tag to render the image inside a Jupyter Notebook. I am not sure about MD files.

> I've migrated beginner/ to `MyST` with the same outputs as production docs

I believe it will render but [ReadTheDocs](https://github.com/executablebooks/jupyter-book/issues/1091) itself does not seem to support this. Do you know if there is a standard place to host jupyter-text projects?

**Comment by rdmolony** [comment]
[jupyter-book](https://github.com/executablebooks/jupyter-book) seems to be hosted on Github Pages, there's a guide [here](https://jupyterbook.org/start/publish.html) which I haven't tried yet

weirdly there doesn't seem to be an associated Github Action in their .github/workflows folder

**Comment by rdmolony** [comment]
To decide:

1. Just use `ipynb` files and close this PR:

Advantages:
- No unpredictability in cell outputs

Disadvantages:
- `git diff`

2. Convert the `ipynb` files to `md` keeping cell outputs as collapsible sections to avoid double outputs if the user decides to run the notebook

Advantages:
- `git diff`

Disadvantages:
- `jupytext` doesn't support saving cell outputs as markdown: mwouts/jupytext#811

3. Convert the `ipynb` files to `md` generating cell outputs at build time

Advantages:
- `git diff`

Disadvantages:
- unpredictable. `jupyter-book` does have a `allow_errors` flag which may catch otherwise hidden bugs

**Comment by rdmolony** [comment]
Does `nbconvert` produce `MyST` markdown or ordinary markdown when saving `ipynb` cell outputs? `jupyter-book` requires `MyST` for execution

**Comment by kvnkho** [comment]
Thanks for laying this out clearly! I want to assume that most users will actually not run the docs. What are you personally leaning towards? I think 2 and 3 are the appropriate compromise? Basically I lean towards the output being rendered when users load the page already.

3 is pretty good also though. Setting `allow_errors = False` gives us build time checks of the code. From a development perspective, 3 is way easier than 2 so I lean towards 3.

**Comment by rdmolony** [comment]
Okay it looks like jupyter-book supports caching in a dir called .jupyter-cache with only changed files being rerun. This could make MyST notebooks viable for docs 

https://jupyterbook.org/content/execute.html

**Comment by rdmolony** [comment]
Thanks Kevin, I agree, 3 looking like a good choice! I think the Github Action log message should confirm for us how caching works in practice when jupyter-book renders the MyST markdown files

**Comment by rdmolony** [comment]
Closing in favour of #82

**Pull request closed without merging**
