### PR TITLE
Proof fugue sql extensions

### PR DESCRIPTION
**Pull request by rdmolony**

### CODE REVIEW

**Comment by rdmolony** [comment]
> `PREPARTITION` can be used along with `Outputters` to apply the logic on each partition but only if the `Outputter interface` is used to define the extension.

@kvnkho what you mind explaining this in more detail?  I don't fully understand. What should a `SQL` only user take away from this?

**Comment by rdmolony** [comment]
`COTRANSFORM` is mentioned but it's created manually by combining `ZIP` and `TRANSFORM`, is `COTRANSFORM` valid `FugueSQL`?  Is there a `FugueSQL` API other than [docs](https://fugue.readthedocs.io/en/latest/api_sql/fugue_sql.html#module-fugue_sql.workflow) and [operators](https://fugue-project.github.io/tutorials/tutorials/fugue_sql/operators.html) that includes `TRANSFORM`, `CREATE` etc?

**Comment by rdmolony** [comment]
Is there a `FugueSQL` API other than [docs](https://fugue.readthedocs.io/en/latest/api_sql/fugue_sql.html#module-fugue_sql.workflow) and [operators](https://fugue-project.github.io/tutorials/tutorials/fugue_sql/operators.html) that includes `TRANSFORM`, `CREATE` etc?

**Comment by kvnkho** [comment]
> > `PREPARTITION` can be used along with `Outputters` to apply the logic on each partition but only if the `Outputter interface` is used to define the extension.
> 
> @kvnkho what you mind explaining this in more detail? I don't fully understand. What should a `SQL` only user take away from this?

Jesus I don't know what I meant unfortunately. Uhhh...this might mean that you need to use the class Outputter like
```python
class MyPlotter(Outputter)
    ....
```

as opposed to
```python
def my_plotter(df) -> None:
    ....
```

But I would double-check if that statement is true.

On the COTRANSFORM, you are exactly right. It is ZIP + TRANSFORM for FugueSQL. Even in the Python interface, I believe it is
```python
df.zip(df2).transform()
```
so there is no cotransform keyword either.

On the API, I guess we don't have a solution like sphinx that can parse the API and you quite literally have to check the grammar file (here)[https://github.com/fugue-project/fugue/blob/master/fugue_sql/_antlr/fugue_sql.g4]

**Comment by kvnkho** [comment]
Confirmed with @goodwanghan that you can use both the class interface and the interfaceless approach (function, decorator, etc.) for an OUTPUTTER with FugueSQL

**Comment by rdmolony** [comment]
Thanks Kevin, so I can remove this line as native, decorator and interface approach are all valid for defining outputters for FugueSQL?

**Comment by kvnkho** [comment]
Yes you can remove the line. The original statement is wrong.

**Comment by kvnkho** [comment]
Closing due to staleness.

**Pull request closed without merging**
