### PR TITLE
Proof index.md

### PR DESCRIPTION
**Pull request by rdmolony**

### CODE REVIEW

**Comment by rdmolony** [comment]
I'm not sure about using distributed computing instead of distributed compute as you refer to it as this a few times

**Comment by kvnkho** [comment]
> I'm not sure about using distributed computing instead of distributed compute as you refer to it as this a few times

Hey @rdmolony , grammarly says to use compute, but I don't have a preference. We can standardize this to `distributed computing`.

Are you going to add more or is this PR done?

**Comment by rdmolony** [comment]
lets go with grammarly!

**Comment by rdmolony** [comment]
we're good when you are

**Review by kvnkho — APPROVED** [review]

**Pull request merged**
